### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by MaartenVerbaarschot** [bluefront/blue4it.nl#1]
- "En je visie op Java bepaald mede de koers van het bedrijf" -> bepaalt
- "Blue4IT’er Brian Vermeer sprak op het grootste Java conferentie" -> de grootste

If you find more typos, just mention them in this ticket as long as it's open

**Comment by martinvisser** [comment]
"Een boegbeeld die kansen maakt." -> boegbeeld dat

**Comment by MichelvanDongen** [comment]
Moet volgens mij wel "een boegbeeld die" zijn

**Comment by MichelvanDongen** [comment]
‘s Middags hield hij een workshop XSS Defense, ‘s Avonds deed hij de ins-and-outs uit de doeken rondom low-risk, high-security webapplicaties -> 's-avonds (kleine "a").

**Comment by martinvisser** [comment]
Het is volgens mij toch echt "het boegbeeld" en du "dat boegbeeld" en niet "de boegbeeld" en daardoor "die boegbeeld".

**Comment by MichelvanDongen** [comment]
de auteur, ondernemer en professor -> graag vervangen door "Venkat"

**Comment by MichelvanDongen** [comment]
Boegbeeld slaat op een persoon, dus zou het "die" moeten zijn. Toch? Ook even gegoogled en dan zie ik ook meestal "die".

**Comment by martinvisser** [comment]
Hmm, misschien moet ik je toch wel gelijk geven :)

**Comment by MichelvanDongen** [comment]
Dank je :)
