### ISSUE TITLE
Visually unclear that you can click on quote stars

### ISSUE THREAD

**Issue by maartenverbaarschot** [bluefront/blue4it.nl#10]
Needs better icon or other way to visually communicate that you can click them for a longer version of the quote

**Comment by MaartenVerbaarschot** [comment]
Ik heb een branch gemaakt hiervoor: 

In die branch heb ik alvast een nieuw icoon gecommit (teksballon met '...' ipv een ster).

Wat er verder nog gedaan moet worden:

- Pulse animatie van de witte cirkel, zoals hier: https://codepen.io/olam/pen/zcqea

**Comment by mrToot** [comment]
Pulse effect on quote & hover rotation Made the icon circle smaller
Made the pulse effect animation
Create an slight rotation on hover to induce the click

**Comment by mrToot** [comment]
#16

**Comment by mrToot** [comment]
#17
